export default function SitemapRobotsIndexPage() {
  return (
    <div>
      <h1>sitemap.ts &amp; robots.ts</h1>
      <p>
        This topic has no interactive UI of its own — the demo is three special files, meant to be hit
        directly:
      </p>
      <ul>
        <li>
          <code>/robots.txt</code> — generated from the project-root <code>app/robots.ts</code>.
        </li>
        <li>
          <code>/sitemap.xml</code> — generated from the project-root <code>app/sitemap.ts</code>; uses{" "}
          <code>new Date()</code>, which is why it classifies as dynamic (ƒ) rather than static (○) —
          see the notes.
        </li>
        <li>
          <code>.../04-sitemap-robots/products/sitemap/0.xml</code>,{" "}
          <code>.../sitemap/1.xml</code>, <code>.../sitemap/2.xml</code> — three separate sitemaps
          generated by <code>generateSitemaps()</code> from a nested <code>products/sitemap.ts</code>,
          each covering a 2-product slice of a 5-product list.
        </li>
      </ul>
    </div>
  );
}
